"""add groups schema

Revision ID: 531f488dd601
Revises: d928e7bdcea3
Create Date: 2026-09-06 13:01:19.358098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531f488dd601'
down_revision: Union[str, Sequence[str], None] = 'd928e7bdcea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_admins',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('group_monitors',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['url_monitor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'monitor_id')
    )
    op.drop_constraint(None, 'url_monitor', type_='foreignkey')
    op.create_foreign_key(None, 'url_monitor', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_monitor', type_='foreignkey')
    op.create_foreign_key(None, 'url_monitor', 'users', ['owner_id'], ['id'])
    op.drop_table('group_monitors')
    op.drop_table('user_groups')
    op.drop_table('group_admins')
    # ### end Alembic commands ###
